/* eslint-disable */
/* Type definitions for zcash-tipbot-native
 * Auto-generated by `napi build` once the addon is compiled on Rust ≥ 1.85.
 * This hand-written copy matches the #[napi] exports in src/lib.rs exactly,
 * so wallet.js gets type checking even before the real build runs.
 */

/** Result of validating a Zcash address against the Unified-only policy. */
export interface AddressValidationResult {
  valid: boolean;
  /** Human-readable rejection reason, or null if valid. */
  reason: string | null;
  /** "unified" | "transparent_p2pkh" | "transparent_p2sh" | "sapling" | "sprout" | "unknown" */
  addressType: string;
}

/** A decoded ZIP-302 tipbot memo. */
export interface DecodedMemo {
  version: number;
  txType: string;
  fromHandle: string | null;
  toHandle: string | null;
  groupName: string | null;
  communityUuid: string;
  message: string | null;
}

/**
 * Derives a ZIP-316 Unified Address for the given diversifier index.
 * @param seedHex - 64-byte BIP-39 seed as lowercase hex
 * @param divIndex - diversifier index as a decimal string (u64 range)
 * @param network - "mainnet" | "testnet"
 */
export function deriveUnifiedAddress(
  seedHex: string,
  divIndex: string,
  network: string
): Promise<string>;

/**
 * Derives the bot's Unified Full Viewing Key for wallet scanning.
 * @param seedHex - 64-byte BIP-39 seed as lowercase hex
 * @param network - "mainnet" | "testnet"
 */
export function deriveUfvk(seedHex: string, network: string): Promise<string>;

/**
 * Converts a BIP-39 mnemonic phrase into a 64-byte seed (hex-encoded).
 * Call once at startup; never log the result.
 */
export function phraseToSeedHex(phrase: string): string;

/**
 * Validates an address for withdrawal, enforcing the Unified-only policy.
 */
export function validateAddress(address: string, network: string): AddressValidationResult;

/**
 * ZIP-317 fee for a transaction with `numActions` logical actions.
 * Returned as a decimal string — parse with BigInt() on the JS side.
 */
export function calculateFee(numActions: number): string;

/** Fee for a standard single shielded send (2 actions = 10000 zatoshis). */
export function standardFee(): string;

/** Fee for a /rain transaction to N recipients (1 + N actions). */
export function rainFee(numRecipients: number): string;

/**
 * Builds and encodes a 512-byte ZIP-302 memo.
 * @returns hex-encoded 512-byte buffer
 */
export function encodeMemo(
  txType: string,
  fromHandle: string | null,
  toHandle: string | null,
  groupName: string | null,
  communityUuid: string,
  message: string | null
): string;

/** Decodes a hex-encoded 512-byte ZIP-302 memo. */
export function decodeMemo(memoHex: string): DecodedMemo;

/** Returns the addon version and build info string. */
export function version(): string;
