/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of address validation — returned to JavaScript as a plain object. */
export interface AddressValidationResult {
  valid: boolean
  /** Human-readable rejection reason, or null if valid. */
  reason?: string
  /**
   * Address type string: "unified" | "transparent_p2pkh" | "transparent_p2sh"
   *                    | "sapling" | "sprout" | "unknown"
   */
  addressType: string
}
/** A decoded tipbot memo — returned to JavaScript as a plain object. */
export interface DecodedMemo {
  version: number
  txType: string
  fromHandle?: string
  toHandle?: string
  groupName?: string
  communityUuid: string
  message?: string
}
/**
 * Derives a ZIP-316 Unified Address for the given diversifier index.
 *
 * Called once per new user during `/register`. The resulting u1... address
 * is stored in SQLite and shown to the user as their deposit address.
 *
 * @param seed_hex   - 64-byte BIP-39 seed as a lowercase hex string
 * @param div_index  - diversifier index (u64); monotonically increasing per user
 * @param network    - "mainnet" or "testnet"
 * @returns          - Unified Address string (u1... or utest1...)
 *
 * # Production
 * This function calls into librustzcash:
 *   zcash_keys::keys::UnifiedSpendingKey::from_seed() →
 *   orchard::keys::FullViewingKey::address_at(DiversifierIndex) →
 *   UnifiedAddress::encode()
 */
export declare function deriveUnifiedAddress(seedHex: string, divIndex: string, network: string): Promise<string>
/**
 * Derives the bot's Unified Full Viewing Key (UFVK).
 *
 * The UFVK allows the wallet scanner to detect all incoming deposits
 * without exposing the spending key. Derive once at startup and cache.
 *
 * @param seed_hex - 64-byte seed as hex string
 * @param network  - "mainnet" or "testnet"
 * @returns        - UFVK encoded string
 */
export declare function deriveUfvk(seedHex: string, network: string): Promise<string>
/**
 * Converts a BIP-39 mnemonic phrase to a 64-byte seed (hex-encoded).
 *
 * @param phrase - space-separated BIP-39 mnemonic (12 or 24 words)
 * @returns      - 64-byte seed as lowercase hex string
 *
 * # Security
 * This function must only be called once at startup and the result held
 * in memory. Never log the return value.
 */
export declare function phraseToSeedHex(phrase: string): string
/**
 * Validates a Zcash address for withdrawal.
 *
 * Enforces the Unified-only policy: rejects transparent (t1.../t3...),
 * Sapling (zs1...), Sprout (zc...), and unknown formats.
 *
 * @param address - the address string to validate
 * @param network - "mainnet" or "testnet"
 * @returns       - { valid: bool, reason: string|null, address_type: string }
 */
export declare function validateAddress(address: string, network: string): AddressValidationResult
/**
 * Calculates the ZIP-317 fee for a transaction with `num_actions` logical actions.
 *
 * fee = max(2, num_actions) × 5_000 zatoshis
 *
 * Standard single send: calculateFee(2) = "10000" zatoshis
 * Rain to 5 users:      calculateFee(6) = "30000" zatoshis
 *
 * Returned as a string to avoid JS Number precision loss above 2^53 zatoshis
 * (zatoshi amounts can exceed Number.MAX_SAFE_INTEGER for very large sends).
 * Parse with `BigInt(result)` on the JS side.
 *
 * @param num_actions - number of logical Orchard actions
 * @returns           - fee in zatoshis as a decimal string
 */
export declare function calculateFee(numActions: number): string
/** Fee for a standard single shielded send (2 actions = 10000 zatoshis). */
export declare function standardFee(): string
/** Fee for a /rain transaction to N recipients (1 + N actions). */
export declare function rainFee(numRecipients: number): string
/**
 * Builds and encodes a 512-byte ZIP-302 memo.
 *
 * @param tx_type        - "tip" | "rain" | "withdrawal" | "deposit"
 * @param from_handle    - sender's Telegram handle (without @), or null
 * @param to_handle      - recipient's Telegram handle, or null
 * @param group_name     - Telegram group title, or null
 * @param community_uuid - bot's COMMUNITY_UUID from .env
 * @param message        - optional human-readable note (truncated if needed)
 * @returns              - hex-encoded 512-byte memo buffer
 */
export declare function encodeMemo(txType: string, fromHandle: string | undefined | null, toHandle: string | undefined | null, groupName: string | undefined | null, communityUuid: string, message?: string | undefined | null): string
/**
 * Decodes a hex-encoded 512-byte ZIP-302 memo.
 *
 * @param memo_hex - hex string of the 512-byte memo field
 * @returns        - decoded memo object
 */
export declare function decodeMemo(memoHex: string): DecodedMemo
/** Returns the addon version and build info. */
export declare function version(): string
